DBAASCLI-69 Add operator deployment check
Percona-Lab/percona-dbaas-cli pull request #100
Opened 2020-04-08 11:28 UTC by nonemax

2020-04-08 11:39 UTC, JNKPercona commented
License check is ok.

2020-04-08 12:02 UTC, delgod approved these changes

2020-04-11 08:53 UTC, JNKPercona commented
License check is ok.

2020-04-16 16:59 UTC, JNKPercona commented
License check is ok.

2020-04-16 20:04 UTC, dAdAbird requested changes
In addition, it's nice to have some integration test that covers introduced cases.

2020-04-16 20:04 UTC, dAdAbird commented on dbaas-lib/engines/k8s-psmdb/psmdb.go
> +			return errors.Errorf("unsupporeted version %s", version)
```go
	switch len(version) {
	case 0:
...
```

but I'd rather go for
```go
	if len(version) == 0 {
		version = defaultVersion
	}
	if _, ok := objects[version]; !ok {
		return errors.Errorf("unsupporeted version %s", version)
	}
```
instead of this switch

2020-04-16 20:04 UTC, dAdAbird commented on dbaas-lib/k8s/cmd.go
> +}
```suggestion
func (p Cmd) GetObjectsElement(typ, name, jsonPath string) ([]byte, error) {
	args := []string{p.execCommand, "get", typ, name, "-o=jsonpath={" + jsonPath + "}"}
	if len(p.Namespace) > 0 {
		args = append(args, []string{"-n", p.Namespace}...)
	}
	data, err = p.runCmd(p.execCommand, args...)
	if err != nil && strings.Contains(err.Error(), "not found") {
		err = ErrNotFound
	}

	return data, err
}
```

2020-04-16 20:04 UTC, dAdAbird commented on dbaas-lib/k8s/cmd.go
> +}
Are you sure "not found" gonna be in the error not in data? `p.runCmd` basically runs `exec.Cmd().CombinedOutput()` which returns both stdout and stderr as the first arg. And the err is for CombinedOutput's errors, not stderr'

2020-04-16 20:04 UTC, dAdAbird commented on dbaas-lib/k8s/cmd.go
> +		_, err = p.runCmd(p.execCommand, "apply", "-f", fileName)
1. Why you need a tmp file? Why the old method doesn't work anymore?
2. In case you need it, use https://golang.org/pkg/io/ioutil/#TempFile and maybe https://golang.org/pkg/os/#TempDir. But no guarantees that tmp dir exists and have accessible permissions. So you have to check it as well.

2020-04-16 20:04 UTC, dAdAbird commented on dbaas-lib/k8s/check.go
> +func (p *Cmd) PreCheck(name, version, operatorName, operatorImage, objectName string, supportedVersions map[string]string) (warnings []string, errArr []error) {
https://github.com/golang/go/wiki/CodeReviewComments#named-result-parameters

> Naked returns are okay if the function is a handful of lines. Once it's a medium sized function, be explicit with your return values.

it's really hard to follow what this method returns

2020-04-16 20:04 UTC, dAdAbird commented on dbaas-lib/k8s/check.go
> +func (p *Cmd) PreCheck(name, version, operatorName, operatorImage, objectName string, supportedVersions map[string]string) (warnings []string, errArr []error) {
Do we have to have errors slice?
As far as I can see you never return more than one error

2020-04-16 20:04 UTC, dAdAbird commented on dbaas-lib/k8s/check.go
> +	return
```go
	if oVersion.Compare(dVersion) != 0 {
		warnings = append(warnings, fmt.Sprintf("%s operator with version %s already installed. Trying work with it", objectName, deployedVersion))
	}
	return
```

2020-04-16 20:04 UTC, dAdAbird commented on dbaas-lib/k8s/cmd.go
> +		err = ErrNotFound
see comments on GetObjectsElement()
and don't overuse "switch" when you can go for "if"

2020-04-16 20:04 UTC, dAdAbird commented on dbaas-cli/cmd/mongo/create.go
> +				log.Println(e)
```suggestion
				log.Println("Error:", e)
```

2020-04-16 20:04 UTC, dAdAbird commented on dbaas-cli/cmd/mongo/create.go
> +			log.Println(w)
```suggestion
			log.Println("Warning:", w)
```

2020-04-16 20:04 UTC, dAdAbird commented on dbaas-cli/cmd/mongo/create.go
> +		}
Maybe it worth to show Warnings as well even there are some errors

2020-04-16 20:04 UTC, dAdAbird commented on dbaas-cli/cmd/mysql/create.go
> +		}*/
?

2020-04-16 20:04 UTC, dAdAbird commented on dbaas-cli/cmd/mysql/delete.go
> +		}*/
?

2020-04-16 20:04 UTC, dAdAbird commented on dbaas-lib/engines/k8s-psmdb/options.go
> +	//	p.conf = c
?

2020-04-16 20:04 UTC, dAdAbird commented on dbaas-lib/engines/k8s-psmdb/options.go
> +	//c := objects[defaultVersion].psmdb
?

2020-04-16 20:04 UTC, dAdAbird commented on dbaas-lib/engines/k8s-psmdb/psmdb.go
> +	defaultVersion = "1.3.0"
Why did you drop Version type?

2020-04-16 20:04 UTC, dAdAbird commented on dbaas-lib/k8s/check.go
> +func (p *Cmd) PreCheck(name, version, operatorName, operatorImage, objectName string, supportedVersions map[string]string) (warnings []string, errArr []error) {
Oh, I see one place. But, according to logic, there are no multiple errors. Either you return some technical error (e.g. supported version, can't parse version etc.) or "no operator + object exists" - in fact, a single error.

2020-04-21 10:56 UTC, JNKPercona commented
License check is ok.

2020-04-22 17:28 UTC, dAdAbird requested changes

2020-04-22 17:28 UTC, dAdAbird commented on dbaas-cli/integtests/k8s-cmd.go
> +	return []byte(o), nil
The only user of this parameter cast it back to a string. So maybe just return string here?

2020-04-22 17:28 UTC, dAdAbird commented on dbaas-lib/engines/k8s-psmdb/psmdb.go
> +	defaultVersion = "1.3.0"
@nonemax ^^^

2020-04-22 17:28 UTC, dAdAbird commented on dbaas-lib/k8s/check.go
> +	}
`err` always will be `nil` if this code reached.
So `return warnings, err` and then `return warnings, nil` looks confusing.
What should be done if `deploymentImage` is empty?

2020-04-22 17:28 UTC, dAdAbird commented on dbaas-cli/integtests/k8s-psmdb.go
> +		return errors.Wrap(err, "run delete-db cmd")
```suggestion
		return errors.Wrap(err, "delete operator deployment")
```

2020-04-22 17:28 UTC, dAdAbird commented on dbaas-lib/k8s/cmd.go
> +	return data, err
`p.runCmd` at the end of the day runs https://pkg.go.dev/os/exec?tab=doc#Cmd.CombinedOutput so there is no way some k8s error may end up in the `err`. `err` could be not nil only if os/exec failed.

2020-04-22 17:28 UTC, dAdAbird commented on dbaas-lib/k8s/cmd.go
> +	//_, err = p.runCmd("sh", "-c", "cat <<-EOF | "+p.execCommand+" apply "+namespace+"-f -\n"+k8sObj+"\nEOF")
do we need this?

2020-04-24 08:08 UTC, JNKPercona commented
License check is ok.

2020-04-24 08:37 UTC, nonemax commented on dbaas-lib/k8s/cmd.go
> +	//_, err = p.runCmd("sh", "-c", "cat <<-EOF | "+p.execCommand+" apply "+namespace+"-f -\n"+k8sObj+"\nEOF")
https://github.com/Percona-Lab/percona-dbaas-cli/pull/100/commits/3f844df711bf1b35c32ec89de8851e67756b6292

2020-04-24 08:38 UTC, nonemax commented on dbaas-cli/integtests/k8s-psmdb.go
> +		return errors.Wrap(err, "run delete-db cmd")
https://github.com/Percona-Lab/percona-dbaas-cli/pull/100/commits/3f844df711bf1b35c32ec89de8851e67756b6292

2020-04-24 08:38 UTC, nonemax commented on dbaas-lib/k8s/check.go
> +	}
https://github.com/Percona-Lab/percona-dbaas-cli/pull/100/commits/3f844df711bf1b35c32ec89de8851e67756b6292

2020-04-24 08:38 UTC, nonemax commented on dbaas-cli/integtests/k8s-cmd.go
> +	return []byte(o), nil
https://github.com/Percona-Lab/percona-dbaas-cli/pull/100/commits/3f844df711bf1b35c32ec89de8851e67756b6292

2020-04-24 08:38 UTC, nonemax commented on dbaas-lib/engines/k8s-psmdb/psmdb.go
> +	defaultVersion = "1.3.0"
https://github.com/Percona-Lab/percona-dbaas-cli/pull/100/commits/3f844df711bf1b35c32ec89de8851e67756b6292

2020-04-24 18:07 UTC, dAdAbird commented on dbaas-lib/k8s/cmd.go
> +	return data, err
> err could be not nil only if os/exec failed.

statement is incorrect. I mean `err` can't contain anything from stderr.

2020-05-01 16:38 UTC, dAdAbird approved these changes

2020-05-04 07:37 UTC, merged