DBAASCLI-73 Refactor cmd files
Percona-Lab/percona-dbaas-cli pull request #104
Opened 2020-05-06 08:10 UTC by nonemax

2020-05-06 08:21 UTC, JNKPercona commented
License check is ok.

2020-05-13 09:36 UTC, dAdAbird requested changes

2020-05-13 09:36 UTC, dAdAbird commented on dbaas-cli/cmd/mongo/create.go
> +	"github.com/Percona-Lab/percona-dbaas-cli/dbaas-cli/cmd/tools"
Avoid generic package names
https://blog.golang.org/package-names#TOC_5.
https://dave.cheney.net/2019/01/08/avoid-package-names-like-base-util-or-common

2020-05-13 09:36 UTC, dAdAbird commented on dbaas-cli/cmd/tools/tools.go
> +	}
what should be done here

2020-05-13 09:36 UTC, dAdAbird commented on dbaas-cli/cmd/mongo/create.go
> +		err := setupOutput(cmd)
consider using PersistentPreRun in parent command

2020-05-19 14:23 UTC, JNKPercona commented
License check is ok.

2020-05-22 20:35 UTC, JNKPercona commented
License check is ok.

2020-05-22 21:45 UTC, JNKPercona commented
License check is ok.

2020-05-22 23:19 UTC, JNKPercona commented
License check is ok.

2020-05-25 16:28 UTC, dAdAbird requested changes

2020-05-25 16:28 UTC, dAdAbird commented on dbaas-cli/cmd/main.go
> +	//},
?

2020-05-25 16:28 UTC, dAdAbird commented on dbaas-cli/cmd/mongo/mongo.go
> +	noWait = noW
Instead of extracting flag and assigning it to the global variable, you may want just parse it into that global variable directly in `init()` like here  https://github.com/Percona-Lab/percona-dbaas-cli/blob/fd9d9b93a95819aa080af8305fb97ff3bcd90755/dbaas-cli/cmd/mysql/create.go#L85-L88

You'd have to move "no-wait" flag from the top level and duplicate it inside `mysql` and `mongo` but it's gonna be more clear. However, you already have a duplication anyway, just in form of highlighted code.

2020-05-25 16:28 UTC, dAdAbird commented on dbaas-cli/cmd/tools/client/client.go
> +package client
In `dbaas-cli/cmd` you have everything related to the cli. And suddenly you put some `tools` package there. It's looking like there is `dbaas-cli tools` command. 
Just rid off of "tools" package. And move "client" and "format" into `dbaas-cli` (on the level along with "pb" package).

2020-05-26 16:07 UTC, JNKPercona commented
License check is ok.

2020-05-26 16:07 UTC, JNKPercona commented
Tests passed

2020-05-26 17:51 UTC, dAdAbird approved these changes

2020-05-26 17:51 UTC, dAdAbird commented on dbaas-cli/cmd/mysql/mysql.go
> +*/
remove pls

2020-05-26 18:20 UTC, JNKPercona commented
Tests failed

2020-05-26 18:33 UTC, JNKPercona commented
License check is ok.

2020-05-26 18:33 UTC, JNKPercona commented
Tests passed

2020-05-27 07:02 UTC, merged