Add psmdb integration
Percona-Lab/percona-dbaas-cli pull request #17
Opened 2019-06-25 18:59 UTC by dAdAbird

2019-07-01 06:35 UTC, nonemax requested changes

2019-07-01 06:35 UTC, nonemax commented on cmd/percona-dbaas/psmdb/psmdb.go
> +// PXCCmd represents the pxc command
s/PXCCmd/PSMDBCmd

2019-07-01 16:28 UTC, delgod approved these changes

2019-07-03 04:42 UTC, delgod approved these changes

2019-07-03 07:53 UTC, nonemax approved these changes

2019-07-03 11:18 UTC, merged