Add update method, add storing instance data in meta
Percona-Lab/percona-dbaas-cli pull request #29
Opened 2019-08-06 10:28 UTC by nonemax

2019-08-07 10:53 UTC, dAdAbird requested changes

2019-08-07 10:53 UTC, dAdAbird commented on broker/controller.go
> +		log.Println("Provision instatnce:", err)
does it make sense to continue with the error?

2019-08-07 10:53 UTC, dAdAbird commented on broker/controller.go
> +	err = c.DeployCluster(instance, &skipS3, instanceID)
are you sure `DeployCluster `?
now both `UpdateServiceInstance` and `CreateServiceInstance` looks identical. is it ok?

2019-08-07 10:53 UTC, dAdAbird commented on broker/controller.go
> +func (c *Controller) getBrokerInstances(typ string) {
it's good to have unit tests for such type of functions

2019-08-07 10:53 UTC, dAdAbird commented on broker/controller.go
> +		return
return errors
don't log it everywhere

2019-08-07 10:53 UTC, dAdAbird commented on dbaas/psmdb/config.go
> +		cr.ObjectMeta.Annotations["broker-instance"] = c.PXC.BrokerInstance
1. make(map[string]string)?
2. **PXC** ? This is why I don't like current design where pxc and psmdb are put together, passed around and everybody knows about everything. That's a huge mess and leads to such kind of errors.

2019-08-12 11:35 UTC, dAdAbird approved these changes

2019-08-12 11:35 UTC, dAdAbird commented on dbaas/psmdb/psmdb.go
> +}
I don't see how and where those two types are used

2019-08-12 12:13 UTC, delgod approved these changes

2019-08-12 12:13 UTC, merged