Add credentials to get, add status to annotation
Percona-Lab/percona-dbaas-cli pull request #47
Opened 2019-08-26 17:44 UTC by nonemax

2019-08-26 18:19 UTC, JNKPercona commented
PXC operator docker - perconalab/percona-xtradb-cluster-operator:master-broker-PR-47-67bfa12

2019-08-27 08:10 UTC, cap1984 approved these changes

2019-08-27 12:19 UTC, dAdAbird commented on broker/cluster.go
> +				log.Println("Error unmarshal crefdentials:", err)
does it make sense to continue with the error?

2019-08-27 14:29 UTC, JNKPercona commented
PXC operator docker - perconalab/percona-xtradb-cluster-operator:master-broker-PR-47-ba2fa7c

2019-08-28 11:26 UTC, dAdAbird requested changes

2019-08-28 11:26 UTC, dAdAbird commented on broker/cluster.go
> +				log.Println("Error unmarshal crefdentials:", err)
s/crefdentials/credentials/

2019-08-28 11:26 UTC, dAdAbird commented on broker/cluster.go
> +					log.Println("Error marshal instance", err)
does it make sense to continue with the error?

2019-08-28 11:26 UTC, dAdAbird commented on broker/cluster.go
> +					log.Println("Error marshal oinstance", err)
the same, does it make sense to continue with an error?

2019-08-28 11:26 UTC, dAdAbird commented on broker/cluster.go
> +	return secret, nil
instead of 
```go
	if err != nil {
		return secret, err
	}

 	return secret, nil
```
just 
```go
return secret, err
```

2019-08-28 11:26 UTC, dAdAbird commented on dbaas/dbaas.go
> +
No need in this method. There is a `GetObject` method which might be used instead.

2019-08-28 11:26 UTC, dAdAbird commented on dbaas/dbaas.go
> +	return nil
instead of 
```go
if err != nil {
	return err
}

return nil
```

just 
```go
return err
```

2019-08-29 11:33 UTC, dAdAbird approved these changes

2019-08-29 12:05 UTC, merged