Comment oplog check
Percona-Lab/percona-dbaas-cli pull request #48
Opened 2019-08-26 18:50 UTC by nonemax

2019-08-26 19:07 UTC, dAdAbird requested changes
That's not a way

2019-08-26 19:25 UTC, JNKPercona commented
PXC operator docker - perconalab/percona-xtradb-cluster-operator:master-broker-PR-48-a545e70

2019-08-26 19:26 UTC, dAdAbird approved these changes

2019-08-26 19:56 UTC, JNKPercona commented
PXC operator docker - perconalab/percona-xtradb-cluster-operator:master-broker-PR-48-3af2e07

2019-08-27 11:38 UTC, delgod approved these changes

2019-08-27 11:39 UTC, merged