CLOUD-371 namespace selection
Percona-Lab/percona-dbaas-cli pull request #51
Opened 2019-08-30 05:39 UTC by nonemax

2019-08-30 06:14 UTC, JNKPercona commented
PXC operator docker - perconalab/percona-xtradb-cluster-operator:master-broker-PR-51-5ba185f

2019-08-30 07:52 UTC, cap1984 approved these changes

2019-08-30 08:19 UTC, delgod commented on broker/cluster.go
> +	dbservice, err = dbaas.New(p.EnvName)
maybe we can pass names pace identical to env? is it have sense?

2019-08-30 10:24 UTC, dAdAbird requested changes

2019-08-30 10:24 UTC, dAdAbird commented on broker/cluster.go
> +	}
No need in check. `dbservice.Namespace` already is an empty string. So if `instance.Context.Namespace == ""`  `dbservice.Namespace` remains the same.

2019-08-30 10:24 UTC, dAdAbird commented on dbaas/dbaas.go
> +	}
Maybe it's better to make the namespace selection the part of the `runCmd` method?

2019-08-30 10:24 UTC, dAdAbird commented on dbaas/delete.go
> +		}
```go
var args []string
if len(p.Namespace) > 0 {
    args = []string{"-n", p.Namespace}
}
out, err := p.runCmd("kubectl", "delete", typ, name, args...)
return errors.Wrapf(err, "get cr: %s", out)
```

2019-09-02 07:41 UTC, JNKPercona commented
PXC operator docker - perconalab/percona-xtradb-cluster-operator:master-broker-PR-51-e9e5ff3

2019-09-02 11:55 UTC, JNKPercona commented
PXC operator docker - perconalab/percona-xtradb-cluster-operator:master-broker-PR-51-7eb7ea3

2019-09-02 16:41 UTC, dAdAbird requested changes
don't panic, see comments

2019-09-02 16:41 UTC, dAdAbird commented on dbaas/dbaas.go
> +//var execCommand string
remove pls

2019-09-02 16:41 UTC, dAdAbird commented on dbaas/dbaas.go
>  		if _, err := exec.LookPath(execCommand); err != nil {
no need in panic below. just return the error

2019-09-02 17:15 UTC, dAdAbird commented on dbaas/dbaas.go
> +			return nil, fmt.Errorf("Unable to find neither '%s' nor '%s' exec files", k8sExecDefault, k8sExecCustom)
```suggestion
			return nil, fmt.Errorf("unable to find neither '%s' nor '%s' exec files", k8sExecDefault, k8sExecCustom)
```

2019-09-02 17:15 UTC, dAdAbird approved these changes

2019-09-03 10:50 UTC, merged