CLOUD-424
Percona-Lab/percona-dbaas-cli pull request #58
Opened 2019-10-23 11:28 UTC by nonemax

2019-10-25 12:09 UTC, dAdAbird requested changes

2019-10-25 12:09 UTC, dAdAbird commented on integtests/apitester/apitester.go
> +	LastOperatiom struct {
s/LastOperatiom/LastOperatio*n*

2019-10-25 12:09 UTC, dAdAbird commented on integtests/apitester/apitester.go
>  			return nil
just `return err`

2019-10-25 12:09 UTC, dAdAbird commented on integtests/apitester/apitester.go
> +			continue
why we log error here instead of return?

2019-10-25 12:09 UTC, dAdAbird commented on integtests/apitester/apitester.go
> +				return errors.New("Wrong resp status")
it's better to have more info on which exactly status should be and what was got instead

2019-10-25 12:09 UTC, dAdAbird commented on integtests/apitester/apitester.go
> +func checkRespData(waitData, respData []byte) error {
s/waitData/expected

2019-10-25 12:09 UTC, dAdAbird commented on integtests/apitester/apitester.go
> +			ticker.Stop()
it's more secure to put ticker.Stop() into defer right after the ticker initialising

2019-10-25 12:09 UTC, dAdAbird commented on integtests/apitester/apitester.go
> +	endTime := startTime.Local().Add(time.Second * time.Duration(250))
1. `time.Now()` already returns `local time`. So no need in `startTime.Local()`. Anyway, it affect neither wall nor monotonic time so `time.Now().UTC().Unix()` always `time.Now().Local().Unix()`. It just makes a confusion here.
2. time.Second * 250

2019-10-25 12:09 UTC, dAdAbird commented on integtests/apitester/apitester.go
> +			fmt.Println()
?

2019-10-25 12:09 UTC, dAdAbird commented on integtests/apitester/apitester.go
> +	"github.com/Percona-Lab/percona-dbaas-cli/integtests/structs"
I don't see this package in the repo

2019-10-25 12:09 UTC, dAdAbird commented on integtests/datafactory/datafactory.go
> +		RespData:   []byte(`{"id":"test-pxc-instance","dashboard_url":"","internalId":"test-pxc-instance","service_id":"percona-xtradb-cluster-id","plan_id":"percona-xtradb-id","organization_guid":"","spac
Why keep this data as a []byte if using it always assumes marshalling into `structs.ServiceInstance`?

2019-10-25 12:09 UTC, dAdAbird commented on integtests/apitester/apitester.go
> +	t.Cases = append(t.Cases, datafactory.GetGetDeletedPSMDBInstanceData())
What a need in this datafactory? why not keep cases as a slice?
Why add extra logic - new object, set, etc.? When it's enough to have a global slice of cases and iterate thru it in function (not a method)  "Run(serverAddress)"

2019-11-01 19:49 UTC, dAdAbird requested changes

2019-11-01 19:49 UTC, dAdAbird commented on integtests/apitester/apitester.go
> +			fmt.Println() // just for create new line after ticker
```suggestion
			fmt.Println() // print a new line after the ticker
```

2019-11-01 19:49 UTC, dAdAbird commented on integtests/apitester/apitester.go
> +			fmt.Println() // just for create new line after ticker
```suggestion
			fmt.Println() // print a new line after the ticker
```

2019-11-01 19:49 UTC, dAdAbird commented on integtests/apitester/apitester.go
>  	startTime := time.Now()
```suggestion

```

2019-11-01 19:49 UTC, dAdAbird commented on integtests/apitester/apitester.go
> +	endTime := startTime.Add(time.Second * 250)
```suggestion
	endTime := time.Now().Add(time.Second * 250)
```

2019-11-01 19:49 UTC, dAdAbird commented on integtests/structs/instance.go
> +)
1. A common style is declaring custom type right above constants that use it. And to group constants by type. Besides no need to declare type along with each const.
```go
type OperationState string

const (
	InProgressOperationSate OperationState = "in progress"
	SucceedOperationState                  = "succeeded"
	FailedOperationState                   = "failed"
)
...
```

2. I don't any usage of those constants in code. Use them!)

2019-11-01 19:49 UTC, dAdAbird commented on integtests/apitester/apitester.go
> +	}
1. Need to pad on what exactly went wrong (what we got and what was expected)
2. Expected data in different cases have a different number of fields. But you make the same checks for each case. If this is the only data that should be checked so no need in extra fields inside the data factory. Or we need a custom check?

2019-11-01 19:49 UTC, dAdAbird commented on integtests/apitester/apitester.go
>  			return fmt.Errorf("cluster not started")
```suggestion
			return errors.New("cluster not started")
```

2019-11-01 19:49 UTC, dAdAbird commented on integtests/apitester/apitester.go
> +		fmt.Printf("\r Wait for cluster. %v tries left  ", (endTime.Unix()-t.Unix())/2)
Are you sure there is should be `\r = CR (Carriage Return)`?

2019-11-01 19:49 UTC, dAdAbird commented on integtests/apitester/apitester.go
> +				return errors.New("Wrong resp status. Have '" + instResp.LastOperation.State + "', want 'succeeded'")
1. "Error strings should not be capitalized"
2. It is definitely something wrong here. You check `status` and `testCase.RespStatus`, but the error contain quite a bit different statements.

2019-11-01 19:49 UTC, dAdAbird commented on integtests/apitester/apitester.go
>  			return err
Add some context to the error.

2019-11-01 19:49 UTC, dAdAbird commented on integtests/apitester/apitester.go
>  		return fmt.Errorf("Wrong status")
```suggestion
		return fmt.Errorf("wrong status")
```

2019-11-06 11:34 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| psmdb | failed |
| pxc | failed |

2019-11-06 11:59 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| pxc | failed |
| psmdb | failed |
| service-broker | passed |

2019-11-06 12:19 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| pxc | failed |
| service-broker | passed |
| psmdb | failed |

2019-11-06 14:29 UTC, dAdAbird requested changes

2019-11-06 14:29 UTC, dAdAbird commented on integtests/apitester/apitester.go
> +		if instResp.LastOperation.State == "succeeded" {
```suggestion
		if instResp.LastOperation.State == structs.SucceedOperationState {
```

2019-11-06 14:29 UTC, dAdAbird commented on integtests/apitester/apitester.go
> +		return errors.New(fmt.Sprintf("wrong state. Have %s, want %s", respInst.LastOperation.State, expected.LastOperation.State))
```go
errors.Errof()
```

2019-11-06 14:29 UTC, dAdAbird commented on integtests/apitester/apitester.go
> +		return errors.New("wrong resp status. Have '" + strconv.Itoa(respStatus) + "', want " + strconv.Itoa(testCase.RespStatus))
Make sense to use `errors.Errorf`

2019-11-06 16:07 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| pxc | failed |
| psmdb | failed |
| service-broker | failed |

2019-11-06 18:08 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| pxc | failed |
| service-broker | passed |
| psmdb | failed |

2019-11-06 18:58 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| psmdb | failed |
| service-broker | passed |
| pxc | failed |

2019-11-07 08:22 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| service-broker | passed |
| psmdb | failed |
| pxc | failed |

2019-11-07 12:34 UTC, dAdAbird approved these changes

2019-11-13 11:16 UTC, delgod approved these changes

2019-11-13 11:16 UTC, merged