CLOUD-497 Add options parsing to psmdb
Percona-Lab/percona-dbaas-cli pull request #74
Opened 2019-12-27 07:34 UTC by nonemax

2020-01-06 12:16 UTC, dAdAbird requested changes
Need more tests cases for the options parsing

2020-01-06 12:16 UTC, dAdAbird commented on dbaas-lib/k8s/cmd.go
> +	}
Shouldn't be here some sleep?

2020-01-06 12:16 UTC, dAdAbird commented on dbaas-lib/options/options.go
> +}
1. `if strings.Contains(s, "[") && strings.Contains(s, "]")` is redundant. Checking `startIndex` and `endIndex` is enough.
2. `if startIndex > 0` means the string starting from the bracket won't be processed. Is it intentional?
3. I don't really understand what this func is intended to do. _I see what it does, but for what?_ It worth to add more test cases

2020-01-06 12:16 UTC, dAdAbird commented on dbaas-lib/options/options.go
> +	//log.Println("type is:", refValue.Addr().Type().Elem().Elem())
remove debug comments pls

2020-01-06 12:16 UTC, dAdAbird commented on dbaas-lib/options/options.go
>  		// TODO: maps, slices
looks like this todo doesn't make sense anymore

2020-01-06 12:16 UTC, dAdAbird commented on dbaas-lib/options/options.go
> +	val.Set(v)*/
Are you sure? why?

2020-01-24 13:28 UTC, merged

2020-02-11 11:49 UTC, AlekSi commented
Do you still need that branch?