Add tests for CLI
Percona-Lab/percona-dbaas-cli pull request #89
Opened 2020-02-19 19:04 UTC by nonemax

2020-02-21 12:28 UTC, dAdAbird requested changes
I'd rather check cluster, not cli output

2020-02-21 12:28 UTC, dAdAbird commented on dbaas-cli/integtests/k8s-psmdb.go
> +		return errors.Wrap(err, "run describe-db for"+psmdb.dbName+" cmd")
use https://pkg.go.dev/github.com/pkg/errors?tab=doc#Wrapf

2020-02-21 12:28 UTC, dAdAbird commented on dbaas-cli/integtests/k8s-psmdb.go
> +		return errors.New("db not start correctly. Output: " + o)
use https://pkg.go.dev/github.com/pkg/errors?tab=doc#Errorf

2020-02-21 12:28 UTC, dAdAbird commented on dbaas-cli/integtests/main.go
> +	cmd := "../cmd/percona-dbaas"
how to get "../cmd/percona-dbaas" binary?

2020-02-21 13:27 UTC, dAdAbird requested changes

2020-02-21 13:27 UTC, dAdAbird commented on dbaas-cli/integtests/main.go
> +	DeleteDB(bool) error
Are you sure you need these methods in the interface since only Run() is used of the objects?

2020-02-25 09:58 UTC, nonemax commented on dbaas-cli/integtests/main.go
> +	cmd := "../cmd/percona-dbaas"
bash script added

2020-02-25 13:12 UTC, dAdAbird approved these changes

2020-02-25 14:20 UTC, merged